version: '2'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUX_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUX_ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUX_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUX_USER_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true

  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUX_ADMIN_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUX_ADMIN_PASSWORD}

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      # Custom env to build the grafana-provisioning/datasources
      DB_SOURCE: ${INFLUX_DATABASE}
      DB_USER: ${INFLUX_USER}
      DB_USER_PASSWORD: ${INFLUX_USER_PASSWORD}
      DB_URL: http://influxdb:8086
      
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      # GF_LOG_FILTERS: rendering:debug
      # GF_LOG_LEVEL: debug

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

  icinga2:
    #image: jordan/icinga2
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    # Set your hostname to the FQDN under which your
    # sattelites will reach this container
    hostname: icinga.dessau.net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      DEFAULT_MYSQL_HOST: mysql
      # Important:
      # keep the hostname influxdb the same as
      # the name of the graphite docker-container
      ICINGA2_FEATURE_INFLUXDB: 1
      ICINGA2_FEATURE_INFLUXDB_HOST: influxdb
      ICINGA2_FEATURE_INFLUXDB_PORT: 8086
      ICINGA2_FEATURE_INFLUXDB_SEND_THRESHOLDS: 'true'
      ICINGA2_FEATURE_INFLUXDB_SEND_METADATA: 'false'
      ICINGA2_FEATURE_INFLUXDB_FLUSH_THRESHOLD: 1024 # How many data points to buffer before forcing a transfer 
      ICINGA2_FEATURE_INFLUXDB_FLUSH_INTERVAL: 10s # How long to buffer data points before transferring to InfluxDB
      ICINGA2_FEATURE_INFLUXDB_DB_NAME: ${INFLUX_DATABASE}
      ICINGA2_FEATURE_INFLUXDB_DB_USER: ${INFLUX_USER}
      ICINGA2_FEATURE_INFLUXDB_USER_PASSWORD: ${INFLUX_USER_PASSWORD}

      ICINGAWEB2_ADMIN_USER: ${ICINGAWEB2_ADMIN_USER}
      ICINGAWEB2_ADMIN_PASS: ${ICINGAWEB2_ADMIN_PASS}
      ICINGA2_USER_FULLNAME: Icinga2 Docker Monitoring Instance
      ICINGA2_FEATURE_GRAFANA: 1

      GRAFANA_USERNAME: ${GRAFANA_USERNAME}
      GRAFANA_PASSWORD: ${GRAFANA_PASSWORD}

      #    volumes:
            # - icinga:/var/cache/icinga2
            # - icinga:/etc/apache2/ssl
            # - icinga:/etc/icinga2
            # - icinga:/etc/icingaweb2
            # - icinga:/var/lib/icinga2
            # - icinga:/var/lib/php/sessions
            # - icinga:/var/log/apache2
            # - icinga:/var/log/icinga2
            # - icinga:/var/log/icingaweb2
            # - icinga:/var/log/mysql
            # - icinga:/var/spool/icinga2
      # Sending e-mail
      #  See: https://github.com/jjethwa/icinga2#sending-notification-mails
      #  If you want to enable outbound e-mail, edit the file mstmp/msmtprc
      #  and configure to your corresponding mail setup. The default is a
      #  Gmail example but msmtp can be used for any MTA configuration.
      #  Change the aliases in msmtp/aliases to your recipients.
      #  Then uncomment the rows below
      # - ./msmtp/msmtprc:/etc/msmtprc:ro
      # - ./msmtp/aliases:/etc/aliases:ro
    ports:
      - "80:80"
      - "443:443"
      - "5665:5665"
    depends_on:
      - mysql
      - influxdb
      - grafana

  mysql:
    image: mariadb
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    volumes:
      - mysql:/var/lib/mysql
      # If you have previously used the container's internal DB use:
      #- ./data/icinga/lib/mysql:/var/lib/mysql

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  icinga:
  mysql:
