#!/bin/bash

. /opt/helpers


if evaluate_boolean "${ICINGA2_FEATURE_INFLUXDB}"; then
	echo "=> Enabling Icinga2 influxdb"
	icinga2 feature enable influxdb
	cat >/etc/icinga2/features-available/influxdb.conf <<-END
object InfluxdbWriter "influxdb" {
        host = "$ICINGA2_FEATURE_INFLUXDB_HOST"
        port = $ICINGA2_FEATURE_INFLUXDB_PORT
        database = "$ICINGA2_FEATURE_INFLUXDB_DB_NAME"
        username = "$ICINGA2_FEATURE_INFLUXDB_DB_USER"
        password = "$ICINGA2_FEATURE_INFLUXDB_USER_PASSWORD"
        enable_send_thresholds = $ICINGA2_FEATURE_INFLUXDB_SEND_THRESHOLDS
        enable_send_metadata = $ICINGA2_FEATURE_INFLUXDB_SEND_METADATA
        flush_threshold = $ICINGA2_FEATURE_INFLUXDB_FLUSH_THRESHOLD
        flush_interval = $ICINGA2_FEATURE_INFLUXDB_FLUSH_INTERVAL
        host_template = {
          measurement = "\$host.check_command$"
          tags = {
            hostname = "\$host.name$"
          }
        }
        service_template = {
          measurement = "\$service.check_command$"
          tags = {
            hostname = "\$host.name$"
            service = "\$service.name$"
          }
        }
}
	END

else
	# Actively disable graphite, to not hit any weird bugs
	icinga2 feature disable influxdb || true
fi
